### ISSUE TITLE
CSV/JSON to M3U

### ISSUE THREAD

**Issue by marat2509** [pawanpaudel93/m3u-parser#18]
Is it possible to implement a reverse function where one can convert a table/file to m3u?

**Comment by pawanpaudel93** [comment]
Yes but is there a standard format for the table/file to convert into m3u ???

**Comment by nikhil96widhani** [comment]
Such a great package but I badly need this feature to make it complete. Following this issue for update

**Comment by pawanpaudel93** [comment]
@marat2509 @nikhil96widhani Please check parse_json and parse_csv methods which are included in the latest version.
