### ISSUE TITLE
Error printed when import

### ISSUE THREAD

**Issue by Impre-visible** [pawanpaudel93/m3u-parser#21]
Hi, When import:
"from m3u_parser import M3uParser"
"INFO" are printed, worst thing ever, can u patch that pls ?

**Comment by pawanpaudel93** [comment]
@Impre-visible Can you show the screenshot of the error you get while importing ??

**Comment by Impre-visible** [comment]
When I import m3u_parser, I have a lot of things printed, with the attribute "INFO:"
![image](https://github.com/pawanpaudel93/m3u-parser/assets/69050895/8806db2d-6664-42c1-8079-535be6b2b76a)
![image](https://github.com/pawanpaudel93/m3u-parser/assets/69050895/7c652779-15b1-4d4d-8016-c8e170a1f705)

but I don't have that when I don't import m3u parser, I think you overwrite the warnings config of the "main" script

**Comment by Impre-visible** [comment]
Normally I just have that :
![image](https://github.com/pawanpaudel93/m3u-parser/assets/69050895/c13400a2-96ec-4bd6-ab5b-e2d7ae5def04)

**Comment by pawanpaudel93** [comment]
@Impre-visible Can you please install the latest version (0.2.1) that I released just now and check if the error persists ??

**Comment by Impre-visible** [comment]
@pawanpaudel93 just tried, it's perfect, thanks 😀
