### ISSUE TITLE
m3u-parser returns empty list

### ISSUE THREAD

**Issue by chaosblog** [pawanpaudel93/m3u-parser#22]
I try to parse an m3u file from an Fritz!Box, that I can access with python requests without problems - m3u-parser returns a empty list.
Since all the entries in the m3u link to rtsp streams I also diasabled the live check.

Here is the (to one entry shortend) content of the m3u-File:
```
#EXTM3U
#EXTINF:0,Dlf
#EXTVLCOPT:network-caching=1000
rtsp://10.0.0.1:554/?avm=1&freq=514&bw=8&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,17,18,20,800,810,850
```

This is my python-code:
```
from m3u_parser import M3uParser
url = "http://10.0.0.1/dvb/m3u/radio.m3u"
parser = M3uParser()
parser.parse_m3u(path= url, check_live=False)
print(parser.get_list())
```

And this is the output from the code:
```
INFO: Started parsing m3u link...
INFO: Parsing completed !!!
[]
```

Is there anything I'm doing wrong or is this a problem with m3u-parser?

**Comment by chaosblog** [comment]
After looking into the closed issues, it seams to be the same thing like in issue #16 - rtsp is missing in the list of correct URI schemes. 
Is there a reason why there are only this few schemes supported? Since tthe IANA has a much longer [list of official registered and allowed schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)

**Comment by pawanpaudel93** [comment]
@chaosblog Closing the issue. You can reopen if this issue is not fixed.
