### ISSUE TITLE
Remove duplicate by (name or name pattern, url)

### ISSUE THREAD

**Issue by mull-codes** [pawanpaudel93/m3u-parser#24]
Please write a method to remove duplicate stream by:
* Name
* Name pattern (optional)
* url

It would be very nice if there could a default call while initialising the object and at object initialisation url and name duplications could be removed

**Comment by pawanpaudel93** [comment]
Hey @mull-codes thanks for the issue. I will update as soon as i finish with this issue.

**Comment by pawanpaudel93** [comment]
Hey @mull-codes, Please install the latest version `0.4.0`. Then you can do the following:

```python
from m3u_parser import M3uParser

parser = M3uParser()
parser.parse_m3u(url)

# Remove all duplicates
parser.remove_duplicates()

# Remove duplicate with name and url
parser.remove_duplicates("Channel 1", "http://example.com/stream1")

# Remove duplicate with name pattern and url
parser.remove_duplicates("Chan.*", "http://example.com/stream1")

# Get the list of streams
print(len(parser.get_list()))
```

**Comment by pawanpaudel93** [comment]
@mull-codes Closing the issue. You can reopen if this issue is not fixed.
